name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.step1.outputs.id }}
    steps:
      - id: step1
        uses: ncipollo/release-action@v1
        with:
          name: "Vollaboard ${{ github.ref_name }}"
          body: |
            See the assets to download this version and install.
          prerelease: false
          draft: false

  build:
    needs: [create-release]
    if: always() && (needs.create-release.result == 'success' || needs.create-release.result == 'skipped')
    permissions: write-all
    runs-on: [self-hosted, yolo]
    container:
      image: docker://fabernovel/android:api-34-v1.8.0
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Jenv
        run: |
          eval "$(jenv init -)"
          jenv global 17

      - uses: actions/cache@v4
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create keystore file and properties from secrets
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_FILE_CONTENTS }}" | base64 --decode > keystore.jks
          cat > keystore.properties <<EOF
          storeFile=keystore.jks
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASS }}
          keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEYSTORE_PASS }}
          EOF

      - name: Build with Gradle
        run: |
          ./gradlew build
          mkdir -p releases
          find app/build/ -type f -name "Vollaboard_Universal.apk" -exec mv {} releases/com.volla.vollaboard-signed.apk \;
          ls -l releases

      - uses: actions/upload-artifact@v4
        with:
          name: com.volla.vollaboard-signed.apk
          path: releases/com.volla.vollaboard-signed.apk

      - name: Upload Apk to GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "releases/com.volla.vollaboard-signed.apk"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ needs.create-release.outputs.releaseId }}
